[config]
keep_std = true
scene_game_list = true

[game_list]
"com.hypergryph.arknights" = [30, 60]
"com.miHoYo.Yuanshen" = [120, 60]
"com.miHoYo.hkrpg" = [120, 60]
"com.kurogame.mingchao" = [24, 30, 45, 60]
"com.tencent.tmgp.speedmobile" = [120,60]
"com.tencent.tmgp.sgame" = [30, 60, 90, 120]
"bin.mt.plus"=[120,60]
[powersave]
margin = 3
core_temp_thresh = 80000

[balance]
margin = 2
core_temp_thresh = 90000

[performance]
margin = 1
core_temp_thresh = 95000

[fast]
margin = 0
core_temp_thresh = 95000
